# Generated by Django 6.0.3 on 2026-03-24 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Заголовок', 'verbose_name_plural': 'Описание'},
        ),
    ]
